import { Point } from '../types';

/**
 * UNIFIED COORDINATE SYSTEM
 * 
 * Physical Units: Centimeters (cm) and Meters (m)
 * World Space: The mathematical 2D space where walls, items, and floors exist.
 * Screen Space: The browser pixels generated by pointer events.
 * 
 * Current mapping: 40 World Units = 1 Meter (1 World Unit = 2.5 cm).
 * 
 * Why PIXELS? In this application, "pixels" (px) refers to World Units, 
 * because at 100% zoom (1.0 scale), 1 World Unit equals 1 Screen Pixel.
 */

export const WORLD_SCALE = {
  PX_PER_METER: 40,
  PX_PER_CM: 0.4,
};

// Available world-space grid steps based on physical dimensions.
export const GRID_SCALES = {
  SCALE_50CM: 50 * WORLD_SCALE.PX_PER_CM, // 20 units
  SCALE_25CM: 25 * WORLD_SCALE.PX_PER_CM, // 10 units
  SCALE_12_5CM: 12.5 * WORLD_SCALE.PX_PER_CM, // 5 units
};

export const getGridSize = (option: 1 | 2 | 3): number => {
  return option === 1 ? GRID_SCALES.SCALE_50CM : option === 2 ? GRID_SCALES.SCALE_25CM : GRID_SCALES.SCALE_12_5CM;
};

// --- Physical Unit Conversions ---

export const cmToPx = (cm: number): number => cm * WORLD_SCALE.PX_PER_CM;
export const pxToCm = (px: number): number => px / WORLD_SCALE.PX_PER_CM;

export const metersToPx = (m: number): number => m * WORLD_SCALE.PX_PER_METER;
export const pxToMeters = (px: number): number => px / WORLD_SCALE.PX_PER_METER;

// --- Area / Distance Formatting Conversions ---

export const pxAreaToSquareMeters = (areaPx: number): number => {
  return areaPx / (WORLD_SCALE.PX_PER_METER * WORLD_SCALE.PX_PER_METER);
};

// --- Coordinate Space Transformations ---

export const screenToWorld = (
  clientX: number,
  clientY: number,
  pan: Point,
  zoom: number,
  containerRect: DOMRect
): Point => {
  return {
    x: (clientX - containerRect.left - pan.x) / zoom,
    y: (clientY - containerRect.top - pan.y) / zoom
  };
};

export const worldToScreen = (
  worldX: number,
  worldY: number,
  pan: Point,
  zoom: number,
  containerRect: DOMRect
): Point => {
  return {
    x: worldX * zoom + pan.x + containerRect.left,
    y: worldY * zoom + pan.y + containerRect.top
  };
};
