import assert from 'node:assert/strict';
import { ITEM_CATALOG } from '../src/catalog';
import { startMobileDrag, moveMobileDrag, resolveMobileDrop } from '../src/utils/mobileItemDrag';
import { attachNearestOpening } from '../src/utils/openingAttachment';
import { documentHistory, initialHistory, emptyDocument } from '../src/utils/documentHistory';
import { MobileGestureOwnership, MobileDragHistoryGate } from '../src/utils/mobileGestureOwnership';

const wall = { id: 'wall', start: { x: 0, y: 0 }, end: { x: 400, y: 0 }, thickness: 8 };
const opening = attachNearestOpening({ id: 'window', typeId: ITEM_CATALOG.find(t => t.shape === 'window')!.id, x: 100, y: 0, rotation: 0 }, [wall])!;
const chair = { id: 'chair', typeId: ITEM_CATALOG.find(t => t.shape === 'bed')!.id, x: 200, y: 100, rotation: 0 };
const doc = { ...emptyDocument(), walls: [wall], items: [opening, chair] };
const before = JSON.stringify(doc);
let history = { ...initialHistory(), present: doc };
const session = startMobileDrag(1, { x: 103, y: 2 }, opening, doc.items, []);
assert.equal(moveMobileDrag(session, { x: 103, y: 2 }, 1), null, 'tap must not move');
const firstPixel = moveMobileDrag(session, { x: 104, y: 2 }, 1)!;
assert.equal(firstPixel[0].wallId, undefined, 'first movement immediately detaches');
assert.equal(firstPixel[0].x, 101);
for (let i = 1; i <= 100; i++) moveMobileDrag(session, { x: 103 + i, y: 2 + i }, 1);
assert.equal(JSON.stringify(doc), before, 'all intermediate frames leave saved document untouched');
assert.equal(history.present, doc);
assert.equal(history.past.length, 0);
assert.equal(history.start, null, 'mobile movement never begins a history transaction');
for (const [dx, dy] of [[80, 50], [-40, 90], [100, -30], [-1, -1], [0, 0]]) {
  const reversed = moveMobileDrag(session, { x: 103 + dx, y: 2 + dy }, 1)!;
  assert.equal(reversed[0].x, opening.x + dx, 'direction change follows finger with no accumulated snap');
  assert.equal(reversed[0].y, opening.y + dy);
}
const raw = moveMobileDrag(session, { x: 133, y: 72 }, 1)!;
assert.equal(raw[0].x, 130, 'final displacement uses start and preserves grab offset');
assert.equal(raw[0].y, 70);
assert.equal(raw[0].wallId, undefined);
const drop = resolveMobileDrop(raw, doc.items, doc.walls, 1, 20, false);
history = documentHistory(history, { type: 'update', exactPlacement: true, update: d => ({ ...d, items: drop.items }) });
history = documentHistory(history, { type: 'commit' });
assert.equal(history.past.length, 1, 'one gesture produces one undo entry');
assert.equal(history.present.items[0].y, 70);
assert.deepEqual(documentHistory(history, { type: 'undo' }).present, doc);
assert.deepEqual(documentHistory(documentHistory(history, { type: 'undo' }), { type: 'redo' }).present, history.present);

// Detached openings at high zoom used to be reattached by the reducer's 24-world-unit rule.
const detached = { ...opening, wallId: undefined, wallOffset: undefined, y: 50 };
const detachedDoc = { ...doc, items: [detached, chair] };
const nearby = resolveMobileDrop([{ ...detached, y: 20 }], detachedDoc.items, doc.walls, 2, 20, false);
assert.equal(nearby.preview?.wall, null, '40 screen pixels is outside mobile attraction');
const exact = documentHistory({ ...initialHistory(), present: detachedDoc }, { type: 'update', exactPlacement: true, update: d => ({ ...d, items: nearby.items }) });
assert.equal(exact.present.items[0].y, 20);
assert.equal(exact.present.items[0].wallId, undefined, 'history must not silently resnap resolved mobile placement');
const near = resolveMobileDrop([{ ...detached, y: 7 }], detachedDoc.items, doc.walls, 2, 20, false);
assert.equal(near.items[0].wallId, wall.id);
assert.equal(near.items[0].y, 0);
assert.equal(resolveMobileDrop([{ ...detached, y: 16 }], detachedDoc.items, doc.walls, 1, 20).items[0].wallId, wall.id);
assert.equal(resolveMobileDrop([{ ...detached, y: 16.01 }], detachedDoc.items, doc.walls, 1, 20).items[0].y, 16.01, 'outside zone preserves exact free position');
const occupied = { ...opening, id: 'occupied' };
const blocked = resolveMobileDrop([{ ...detached, y: 10 }], [detached, occupied], doc.walls, 1, 20, false);
assert.equal(blocked.preview?.valid, false);
assert.equal(blocked.items[0].y, 10, 'blocked target does not freeze or jump back');
assert.equal(blocked.items[0].wallId, undefined);

const group = startMobileDrag(2, { x: 0, y: 0 }, chair, doc.items, [chair.id, opening.id]);
const groupRaw = moveMobileDrag(group, { x: 27, y: 63 }, 1)!;
const groupDrop = resolveMobileDrop(groupRaw, doc.items, doc.walls, 1, 20, false);
assert.equal(groupDrop.items[1].x - groupDrop.items[0].x, chair.x - opening.x);
assert.equal(groupDrop.items[0].wallId, undefined);
const furniture = startMobileDrag(3, { x: 200, y: 100 }, chair, doc.items, []);
const furnitureRaw = moveMobileDrag(furniture, { x: 257, y: 163 }, 1)!;
assert.equal(furnitureRaw[0].x, 257, 'furniture tracks finger without grid sticking');
assert.equal(resolveMobileDrop(furnitureRaw, doc.items, doc.walls, 1, 20, true).items[1].x, 257);
assert.equal(resolveMobileDrop(furnitureRaw, doc.items, doc.walls, 1, 20).items[1].y, 163, 'default drop is exact');
assert.notEqual(resolveMobileDrop(furnitureRaw, doc.items, doc.walls, 1, 20, false).items[1].y, 163, 'explicit snapping still works at release');
assert.deepEqual(documentHistory(documentHistory({ ...initialHistory(), present: doc }, { type: 'begin' }), { type: 'cancel' }).present, doc);
console.log('Mobile drag: immutable frames, grab offset, free movement, screen-space snap, blocked walls, groups, exact persistence and single-step undo passed.');

const ownership = new MobileGestureOwnership();
const gate = new MobileDragHistoryGate();
assert.equal(ownership.down(1, 'object'), 'object');
assert.equal(gate.down(1, true), true, 'object bypasses global history');
assert.equal(ownership.down(2, 'empty'), 'ignored', 'second finger must never enter viewport');
assert.equal(gate.down(2, false), true);
assert.equal(ownership.owner, 1);
ownership.up(2); // pointercancel / lostpointercapture for extra finger
assert.equal(gate.end(2), true, 'extra finger cancellation cannot cancel history');
assert.equal(ownership.owner, 1, 'extra finger cancellation preserves owner');
assert.equal(ownership.objectGesture, true);
assert.equal(ownership.down(3, 'empty'), 'ignored');
ownership.up(1);
assert.equal(ownership.objectGesture, true, 'remaining finger cannot become pan');
assert.equal(ownership.down(4, 'empty'), 'ignored');
ownership.up(3); ownership.up(4);
assert.equal(ownership.objectGesture, false);
assert.equal(ownership.down(5, 'empty'), 'empty');
assert.equal(ownership.down(6, 'object'), 'ignored', 'empty plus object cannot pinch');
ownership.up(6);
assert.equal(ownership.down(7, 'empty'), 'empty', 'two empty starts can pan and zoom');
ownership.clear();
assert.equal(ownership.owner, null);
assert.equal(gate.end(1), true);
assert.equal(gate.down(8, false), false, 'desktop and other edits retain normal history');
console.log('Mobile ownership: object priority, secondary cancellation, remaining-finger isolation, empty-only pinch and history exclusion passed.');
