import assert from 'node:assert/strict';
import { mock } from 'node:test';
import { CollaborationLoop, safePeers, guestToken, cursorColor } from '../src/cloud/collaboration';
mock.timers.enable({ apis: ['setTimeout', 'Date'], now: 10000 });
let finish: (()=>void) | undefined;
let visible=true;
const calls: unknown[]=[];
const loop=new CollaborationLoop(async c=>{ calls.push(c); await new Promise<void>(resolve=>{finish=resolve;}); },()=>visible);
loop.point({x:1,y:2,view:'2d'});
mock.timers.tick(0);
assert.equal(calls.length,1);
for(let i=0;i<50;i++) loop.point({x:i,y:0,view:'2d'});
mock.timers.tick(100);
assert.equal(calls.length,1,'No concurrent cursor requests');
finish!(); await Promise.resolve(); await Promise.resolve();
loop.point({x:99,y:0,view:'2d'});
mock.timers.tick(99);
assert.equal(calls.length,1,'Throttle rapid movement');
mock.timers.tick(1);
assert.deepEqual(calls[1],{x:99,y:0,view:'2d'},'Send newest cursor only');
finish!(); await Promise.resolve(); await Promise.resolve();
visible=false; mock.timers.tick(1000); await Promise.resolve();
assert.equal(calls.length,2,'Hidden tabs do not issue requests');
loop.stop(); mock.timers.tick(10000);
assert.equal(calls.length,2,'Dispose stops requests');
let attempts=0;
const recovering=new CollaborationLoop(async()=>{
  attempts++;
  if(attempts===1) recovering.retryAfter(5000);
},()=>true);
recovering.wake(); mock.timers.tick(0); await Promise.resolve(); await Promise.resolve();
recovering.point({x:10,y:20,view:'2d'});
mock.timers.tick(4999);
assert.equal(attempts,1,'Movement cannot bypass outage backoff');
mock.timers.tick(1); await Promise.resolve(); await Promise.resolve();
assert.equal(attempts,2,'Collaboration recovers without reloading after service returns');
recovering.stop();
mock.timers.reset();
assert.equal(guestToken('https://roomplan.online/#guest=abc'),'abc');
assert.equal(guestToken('https://roomplan.online/?share=abc'),null);
assert.equal(safePeers([{id:'a',name:'A',cursor:{x:NaN,y:0,view:'2d'}}])[0].cursor,null);
assert.equal(safePeers([{id:'a',name:'A',cursor:{x:1,y:2,view:'2d'}}]).length,1);
assert.equal(cursorColor('a'),cursorColor('a'));
console.log('Cursor batching, throttling, hidden tabs, disposal and payload validation passed');
