import assert from 'node:assert/strict';
import { attachNearestOpening, reconcileOpenings, openingValidationError } from '../src/utils/openingAttachment';
import { emptyDocument, documentHistory, initialHistory } from '../src/utils/documentHistory';
import { parseProject, serializeProject } from '../src/utils/projectFile';
import { ITEM_CATALOG } from '../src/catalog';
const wall = { id: 'wall', start: { x: 0, y: 0 }, end: { x: 200, y: 0 }, thickness: 8 };
const door = { id: 'door', typeId: ITEM_CATALOG.find(type => type.shape === 'door')!.id, x: 80, y: 10, rotation: 1 };
const attached = attachNearestOpening(door, [wall])!;
assert.equal(attached.y, 0);
assert.equal(attached.rotation, 0);
const original = { ...emptyDocument(), walls: [wall], items: [attached] };
const translated = reconcileOpenings(original, { ...original, walls: [{ ...wall, start: { x: 20, y: 30 }, end: { x: 220, y: 30 } }] });
assert.equal(translated.items[0].x, 100);
assert.equal(translated.items[0].y, 30);
const rotated = reconcileOpenings(original, { ...original, walls: [{ ...wall, end: { x: 0, y: 200 } }] });
assert.equal(rotated.items[0].x, 0);
assert.equal(rotated.items[0].y, 80);
assert.equal(rotated.items[0].rotation, Math.PI / 2);
assert.equal(reconcileOpenings(original, { ...original, walls: [{ ...wall, end: { x: 5, y: 0 } }] }), original);
assert.equal(reconcileOpenings(original, { ...original, walls: [] }).items[0].wallId, undefined);
assert.deepEqual(parseProject(serializeProject(original)), original);
let history = { ...initialHistory(), present: original };
history = documentHistory(history, { type: 'update', update: () => translated });
history = documentHistory(history, { type: 'undo' });
assert.deepEqual(history.present, original);
console.log('Openings: attachment, translation, rotation, fit rejection, wall deletion, persistence and undo passed.');

const overlapping = { ...original, items: [attached, { ...attached, id: 'second' }] };
assert.match(openingValidationError(overlapping)!, /overlap/);
assert.equal(reconcileOpenings(original, overlapping), original);
assert.throws(() => parseProject(serializeProject(overlapping)), /overlap/);
assert.throws(() => parseProject(serializeProject({ ...original, items: [{ ...attached, wallOffset: 9999 }] })), /fit/);
assert.throws(() => parseProject(serializeProject({ ...original, items: [{ ...attached, y: 100 }] })), /position/);
const rejected = documentHistory({ ...initialHistory(), present: original }, { type: 'update', update: () => overlapping });
assert.deepEqual(rejected.present, original);
assert.equal(rejected.past.length, 0);
assert.match(rejected.error!, /not applied/);
const separated = attachNearestOpening({ ...door, id: 'second', x: 160 }, [wall])!;
assert.equal(openingValidationError({ ...original, items: [attached, separated] }), null);
console.log('Opening safeguards: overlap rejection, import fit/position validation, visible errors and unchanged history passed.');
