import { PGlite } from '@electric-sql/pglite';
import { readFileSync, readdirSync } from 'node:fs';
import assert from 'node:assert/strict';
import {ProjectSync} from '../src/cloud/ProjectSync';
import {emptyDocument} from '../src/utils/documentHistory';
const db=new PGlite();
await db.exec(`create role anon;create role authenticated;create schema auth;create table auth.users(id uuid primary key,email text,email_confirmed_at timestamptz);create function auth.uid() returns uuid language sql stable as $$select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid$$;grant usage on schema auth to authenticated;grant execute on function auth.uid() to authenticated;`);
const files=readdirSync('supabase/migrations').sort();
for(const file of files.slice(0,-1))await db.exec(readFileSync('supabase/migrations/'+file,'utf8'));
const owner='00000000-0000-0000-0000-000000000001';
await db.query('insert into auth.users values($1,$2,now())',[owner,'test@example.com']);
await db.query("select set_config('request.jwt.claim.sub',$1,false)",[owner]);await db.exec('set role authenticated');
const rpc=async(name:string,args:unknown[]) => (await db.query<any>(`select to_jsonb(public.${name}(${args.map((_,i)=>'$'+(i+1)).join(',')})) as result`,args)).rows[0].result;
const id=await rpc('rp_create_project',['Autosave audit']);
const load=async()=> (await db.query<any>('select * from public.rp_projects where id=$1',[id])).rows[0];
const transport={load,save:async(_id:string,changes:any)=>rpc('rp_save_changes',[id,JSON.stringify(changes)])};
const initial=await load();const first=new ProjectSync(initial,'owner',transport,()=>{});
const island={id:'island',typeId:'kit_japanese_complete',x:200,y:200,rotation:0,panelState:'half' as const,panelMaterial:'woven' as const};
first.changed({...emptyDocument(),items:[island]},false);await first.saveNow();assert.match(first.error,/migration/);assert.equal((await load()).revision,0);assert(first.dirty);
await db.exec('reset role');await db.exec(readFileSync('supabase/migrations/'+files.at(-1),'utf8'));await db.exec('set role authenticated');
await first.saveNow();assert.equal(first.dirty,false);assert.deepEqual((await load()).document.items,[island]);
const second=new ProjectSync(await load(),'editor',transport,()=>{});
first.changed({...first.draft,comments:[{id:'one',x:0,y:0,text:'First editor'}]},false);
second.changed({...second.draft,comments:[{id:'two',x:0,y:0,text:'Second editor'}]},false);
await Promise.all([first.saveNow(),second.saveNow()]);
const together=await load();assert.equal(together.document.comments.length,2);
first.receive(together);second.receive(together);
first.changed({...first.draft,items:[{...island,x:300}]},false);second.changed({...second.draft,items:[{...island,x:400}]},false);
await first.saveNow();await second.saveNow();assert(second.conflict);await second.saveNow();assert(second.conflict);assert.equal(second.draft.items[0].x,400);assert.equal((await load()).document.items[0].x,300);
first.dispose();second.dispose();
const reopened=new ProjectSync(await load(),'owner',transport,()=>{});assert.equal(reopened.draft.items[0].x,300);assert.equal(reopened.draft.comments.length,2);reopened.dispose();
await db.close();console.log('PASS: local PostgreSQL RPC/read-back, missing newest catalog migration rejection and retry, new objects, two editor sessions independent merge, same-object conflict/retry protection, reopen from persisted document. No production database used.');
