import assert from 'node:assert/strict';
import { predictOpeningDrag } from '../src/utils/openingDrag';
import { attachNearestOpening, reconcileOpenings, nudgeOpeningAlongWall } from '../src/utils/openingAttachment';
import { emptyDocument } from '../src/utils/documentHistory';
import { ITEM_CATALOG } from '../src/catalog';
const wall = { id: 'a', start: { x: 0, y: 0 }, end: { x: 300, y: 0 }, thickness: 8 };
const other = { ...wall, id: 'b', start: { x: 0, y: 100 }, end: { x: 300, y: 100 } };
const item = attachNearestOpening({ id: 'window', typeId: ITEM_CATALOG.find(t => t.shape === 'window')!.id, x: 80, y: 0, rotation: 0 }, [wall])!;
const walls = [wall, other];
const preview = predictOpeningDrag({ ...item, x: 130, y: 90 }, walls, [item], 1, wall.id);
assert.equal(preview.wall?.id, other.id);
assert.equal(preview.valid, true);
assert.equal(item.y, 0, 'preview must not mutate the source');
const doc = { ...emptyDocument(), walls, items: [item] };
assert.deepEqual(reconcileOpenings(doc, { ...doc, items: [preview.placement!] }).items[0], preview.placement, 'drop must match the preview');
assert.equal(predictOpeningDrag({ ...item, y: 52 }, walls, [item], 1, wall.id).wall?.id, wall.id, 'small jitter retains target');
assert.equal(predictOpeningDrag({ ...item, y: 55 }, walls, [item], 1, wall.id).wall?.id, other.id, 'deliberate movement switches target');
assert.equal(predictOpeningDrag({ ...item, y: 60 }, [wall], [item], 1).valid, false);
assert.equal(predictOpeningDrag({ ...item, y: 30 }, [wall], [item], 2).valid, false, 'attraction uses screen pixels');
const occupied = { ...preview.placement!, id: 'occupied' };
assert.equal(predictOpeningDrag({ ...item, x: 130, y: 90 }, walls, [item, occupied], 1).valid, false);
assert.equal(predictOpeningDrag(item, [{ ...wall, end: { x: 5, y: 0 } }], [item], 1).placement, null);
console.log('Opening drag: prediction, exact drop, hysteresis, zoom, collisions and fit passed.');

const vertical = { ...wall, end: { x: 0, y: 300 } };
const hosted = attachNearestOpening({ ...item, x: 0, y: 100 }, [vertical])!;
assert.equal(nudgeOpeningAlongWall(hosted, [vertical], 4, 0).y, hosted.y + 4);
assert.equal(nudgeOpeningAlongWall(hosted, [vertical], 0, -4).y, hosted.y - 4);
assert.equal(nudgeOpeningAlongWall(hosted, [vertical], 4, 0).x, 0);
const shifted = nudgeOpeningAlongWall(hosted, [vertical], 4, 0);
const hostedDoc = { ...emptyDocument(), walls: [vertical], items: [hosted] };
assert.deepEqual(reconcileOpenings(hostedDoc, { ...hostedDoc, items: [shifted] }).items[0], shifted);
console.log('Window joystick: horizontal/vertical input follows the host wall and survives reconciliation.');
