import assert from 'node:assert/strict';
import { documentHistory as reduce, initialHistory, emptyDocument } from '../src/utils/documentHistory';

let state = initialHistory();
state = reduce(state, { type: 'update', update: d => ({ ...d, floors: [{ id: 'floor', color: 'white', points: [{ x: 0, y: 0 }, { x: 40, y: 0 }, { x: 40, y: 40 }] }] }) });
const original = state.present;
state = reduce(state, { type: 'update', update: emptyDocument });
assert.equal(state.present.floors.length, 0);
state = reduce(state, { type: 'undo' });
assert.deepEqual(state.present, original);
state = reduce(state, { type: 'redo' });
assert.equal(state.present.floors.length, 0);
state = reduce(state, { type: 'undo' });
const beforeDrag = state.past.length;
state = reduce(state, { type: 'begin' });
for (let x = 1; x <= 50; x++) state = reduce(state, { type: 'update', update: d => ({ ...d, comments: [{ id: 'note', text: '', x, y: 0 }] }) });
assert.equal(state.past.length, beforeDrag);
state = reduce(state, { type: 'commit' });
assert.equal(state.past.length, beforeDrag + 1);
assert.equal(state.future.length, 0, 'editing after undo discards redo');
state = reduce(state, { type: 'undo' });
assert.deepEqual(state.present, original);
state = reduce(state, { type: 'begin' });
state = reduce(state, { type: 'update', update: emptyDocument });
state = reduce(state, { type: 'cancel' });
assert.deepEqual(state.present, original);
assert.equal(state.future.length, 1, 'cancel preserves redo');
state = reduce(state, { type: 'begin' });
state = reduce(state, { type: 'update', update: emptyDocument });
state = reduce(state, { type: 'update', update: () => original });
state = reduce(state, { type: 'commit' });
assert.equal(state.future.length, 1, 'returning to starting geometry is not a new edit');
for (let x = 0; x < 150; x++) state = reduce(state, { type: 'update', update: d => ({ ...d, comments: [{ id: 'note', text: '', x, y: 0 }] }) });
assert.equal(state.past.length, 100);
console.log('Document history: clear/undo/redo, gesture grouping, cancellation, branching, no-op and history limit passed.');
